### ISSUE TITLE
Can *some* assets be proprietary but the entry qualify as open-source?

### ISSUE THREAD

**Issue by eishiya** [gbdev/gbcompo21#3]
A friend and I are considering entering, and I would like to make our project open-source, but the idea they'd most like to do is a prototype for a commercial game they want to make later. They want to keep the character sprites proprietary while allowing all the code, music, and background art to be freely licensed, because they're not comfortable with the idea of their character designs showing up in other games.

Would a game whose OSS repo excludes many of the sprites but include everything else qualify as OSS, or would excluding any part of the assets disqualify the entry for those additional prizes?

**Comment by ISSOtm** [comment]
I'm in favor of counting "partial" repos as open-source as long as what *is* published is significant and reusable, even if it can't outright be compiled to the final game, as being in the spirit of the bonus ("contribute something others will be able to reuse", right?).

(Mind that ripping assets is very easy for GB games, so *excluding* the artwork from the repo is unlikely to do much; including it with an explicit non-permissive license would be more efficient, I believe.)

**Comment by bbbbbr** [comment]
Some other options that come to mind: 
- The sprites could be under a "open", but more restrictive license such as CC BY-NC-ND: (Credit must be given, Non-commercial distribution only, No derivatives or adaptations of the work are permitted)
- The sprites in the repo could be replaced by some simpler version which would allow the project to still build

**Comment by eishiya** [comment]
> (Mind that ripping assets is very easy for GB games, so _excluding_ the artwork from the repo is unlikely to do much; including it with an explicit non-permissive license would be more efficient, I believe.)

This is a good point, and a good idea.

Fortunately, my friend and I were able to come up with an alternative idea, so we can sidestep this problem entirely. I'm looking forward to giving it a go come July!

**Comment by ISSOtm** [comment]
I think this issue is still worth pinning or pointing out, since others are likely to ask the same question. Should we?

**Comment by avivace** [comment]
> I think this issue is still worth pinning or pointing out, since others are likely to ask the same question. Should we?

I agree, we can add this as an entry in the "FAQ" section of the rules

**Comment by bbbbbr** [comment]
Added a reference from FAQ 14 as "See __this issue__ for further details".
Could convert it to a full on item if others prefer it.

**Comment by avivace** [comment]
> Some other options that come to mind:
> 
>     * The sprites could be under a "open", but more restrictive license such as CC BY-NC-ND: (Credit must be given, Non-commercial distribution only, No derivatives or adaptations of the work are permitted)
> 
>     * The sprites in the repo could be replaced by some simpler version which would allow the project to still build

I'm closing this considering this resolution as official:

- Use a less permissive CC licence
- As long as the *code* is there, you can replace the sprites / assets with lower resolution ones

**Comment by GeekJoystick** [comment]
Hey, so I'm wondering, how much can sprites and other assets be simplified in order to still count as open source?
(What I'd like to do in the best of worlds is to be able to open the game engine to open source, but not the entire game (so as little data as needed to compile, maybe some demo version? idk), so that people can't just straight up take what we've worked hard to make, but still can modify the engine and create their own contents?)

**Comment by bbbbbr** [comment]
After some discussion among organizers: the open sourced assets should be sufficient to play and enjoy the game (in a way that's similar to the final entry), otherwise it's just an engine that is being open sourced and not the game itself (the spirit of the bonus is to encourage open and shared code/content of the games entered in the compo).
