### ISSUE TITLE
How can the awarding of prizes overlap, and how can it not?

### ISSUE THREAD

**Issue by dori4n** [gbdev/gbcompo21#4]
What does
> Each entry competes only in the leaderboard for its category.

mean in combination with
> The "Best OSS entry in the category" can overlap with the other prizes in the same category

and
> The "Best Games rleased as OSS" can overlap with the other awards in "Best games"

*^ that's a real typo in that [Google Docs spreadsheet](https://docs.google.com/spreadsheets/d/196vIZGLbSk1ewzRnZc7Dy_LJdPQpfJUg-udT4iyBVOg "gbcompo21 prizes - Google Sheets"), btw*

That prizes can overlap in all the various ways if certain things are made and/or made a certain way seems obvious in a way, what this means in practice isn't really sufficiently explained and spelled out, though. Does it mean the higher prize is awarded, that awarding of a prize excludes awarding a prize in another category (including, but not limited to, the judges weighing their options among competing entries over who gets what crown), that both are awarded, or something somewhere in-between all those options, depending on the category?

**Comment by avivace** [comment]
Each entry competes in 1 and only 1 category: Games, Demo, Tool or Music.

The Games category has 2 "rankings" and has awards for both of them:

- The first leaderboard ranks every entry in the category and the first 5 entries are awarded.
- The second leaderboard ranks every entry in the category which is ALSO released as OSS.

If an entry happens to be ranked in both leaderboards, it gets awards for both.
