### ISSUE TITLE
What qualifies as "open source"?

### ISSUE THREAD

**Issue by dori4n** [gbdev/gbcompo21#5]
Where's the limit of what still qualifies as "open source"? 
Is publishing code with "all rights reserved" enough or must it be a permissive "copyleft" license or even one from a selection of approved licenses (i.e, you can't write your own)?
Any other peculiarities I've overlooked?

**Comment by aaaaaa123456789** [comment]
Let's not reinvent the wheel. The FSF and the OSI have a list of free and open source licenses. Anything from that list is free/open source.

**Comment by dori4n** [comment]
> The FSF and the OSI have a list of free and open source licenses.

That is not what I asked. Does it have to be "free", or is some variant of non-free permissible (if Creative Commons is allowed, some of those would not qualify as "free" to FSF, OSI or GNU standards, for example). I want to know where the limit is under which an entry can no longer be considered as "open source", and "non-free" isn't it.

* **Which minimal tenets does the license need to satisfy to qualify?**
* Is merely being able to read the code enough?
* Is some part of copy permission (apart from download to view in a browser) required?
* Do people who are able to access the code need to be able to download it, compile it and run it?
* Does the above need to be happening on hardware they own?
* Do they need to be able to make derivative works?
* Can I ask, that if they make a derivative work of any kind, that they publish it and send me a copy, no matter how small the change?
* Can I place restrictions on what changes they are allowed to make and publish?
* Can I ask that they pay for the privilege to use the code and/or assets in any manner but to look at it and to learn the method of doing a particular thing?
* If someone happens to hold a patent on any method used or the author of art assets used would like to reserve certain rights on their use (including, but not limited to, the case that both of those are me), can I extend a license that places the same restrictions on the entire work as required? (sort of encroaches on *#3*)

**Comment by avivace** [comment]
1. You have to publish the game code (and assets) on a *public* repository. We accept GitHub and GitLab as git hosts.
2. Code must be licensed GPL, MIT, Apache or CC0. We may discuss on accepting other licenses approved by FSF and OSI. Assets must be licensed with any of the CC licenses.
3. Obfuscated code, non-reproducible builds, intentionally making the source code hard to read/re-use will exclude the entry form the OSS leaderboards. This is at discretion of the hosts and judges. I must be able to read the code and compile it into a working ROM, running a script or following istructions. We are giving additional prizes to promote OSS software, not to award people circumventing rules.
4. Every other point your mentioned is pretty much covered by the terms of the license you would choose, so I'm sure what do you want to discuss here (Derivative work, allowed changes, restrict-able changes, ..).

Points 1 and 2 are clearly covered by **Rule 14**.

**Comment by ISSOtm** [comment]
The spirit of the "open-source" bonus is to encourage code reusability and reuse; publishing the code but preventing its use, obfuscation, etc. do not work towards that goal.

**Comment by dori4n** [comment]
> Code must be licensed GPL, MIT, Apache or CC0.

Those would all be too permissive.

> I must be able to read the code and compile it into a working ROM, [...] following istructions.

That would be acceptable. Do those instructions need to be part of the public repository? I am okay with a skilled person being able to compile the ROM as a reward for having acquired said skills, with an unskilled one who just wants to run it, not as much.

> Every other point your mentioned is pretty much covered by the terms of the license you would choose [...]

I would most prefer to be allowed to write it myself. It would likely be very short on the order of permissions granted. The reason I have asked about this is, because I want to know if those things are important to you and to be able to assess, if making an entry while publishing code is worthwhile or not. If you require that I do any of the things I am not okay with doing, or too many of those I might be willing to do, I might have to decide against it (either because it would incur me prohibitive costs somehow, or because I simply don't want to).

**Comment by avivace** [comment]
> > Code must be licensed GPL, MIT, Apache or CC0.
> 
> Those would all be too permissive.

Nobody forces you to submit your entry as OSS.

**Comment by dori4n** [comment]
> Nobody forces you to submit your entry as OSS.

Obviously. But if I can do it, I might want to. If you don't want to entertain the discussion of having your cake and eating it too, I can understand that.

**Comment by aaaaaa123456789** [comment]
In the end, the concept of open source is [very well defined](https://opensource.org/osd); it seems to me that what you're trying to do isn't OSS at all, at least according to the generally accepted definition.

**Comment by dori4n** [comment]
> it seems to me that what you're trying to do isn't OSS at all, at least according to the generally accepted definition

From that link, yes, in this particular case, I am not okay with numbers 1, parts of 2 (notably sentence 1 and the implications of sentences 2 and 3), 3, parts of 4 (notably sentence 2), 5, 6, partially 7, 8, 9 and 10 (actually, I'm not sure how that would apply here, maybe I don't need to object to 10, better safe than sorry).
Because what that list notably describes is "free" software not "open source". I am okay with open source, but not with free as in freedom (or even, and especially not free of charge) unless it's paid for at least at cost. The digital form of look but don't touch, if you will.

I might, with some limitations, be amenable to apply some variation of [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/ "Creative Commons — Attribution-NonCommercial-NoDerivatives 4.0 International
  — CC BY-NC-ND 4.0 ") to some form of work, but that's not a "free" license either (and [not for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software "Frequently Asked Questions - Creative Commons | Can I apply a Creative Commons license to software?")). And I would very much like an additional stipulation of a non-distribute clause added to it, meaning, if someone wants a copy they come to me to get it, always. And in the case of binary form, I would want that they pay for a copy until the development costs have been covered unless they're skilled enough to solve a "you don't get compile instructions" puzzle (yes, this is discrimination, against unskilled individuals specifically, and I don't care if they look at me funny for it, learning is free). After that I'm open to anything, probably, unless this happens too fast to give those able a chance to acquire some new skills. Someone else might have other interests, if this was a collaborative work, though.

**Comment by aaaaaa123456789** [comment]
What you call "open source" is generally called "source available": in other words, the source is _there_, you can access it, but it's _not_ open source. (For instance, the popular sprite editor Aseprite is a source-available program.) Open source is _not_ just making the source available, and your source available approach is simply not what we're looking for.

**Comment by dori4n** [comment]
> What you call "open source" is [...]

And at this point it's all about semantics, word choice and what the marketing folks like to use, and while we could talk about that all day, I have better things to do. ❤️

**Comment by ISSOtm** [comment]
Applying a "no derivatives" clause to your entry does not prevent you from participating, and we respect people who wish to do so. The bonus, however, is for people who agree to contribute their efforts to the community at large; if you refuse to do so, *it's fine, and we respect that*.
