### ISSUE TITLE
What qualifies as a "known MBC"? (Rule 11)

### ISSUE THREAD

**Issue by dori4n** [gbdev/gbcompo21#6]
[Rule 11](https://github.com/gbdev/gbcompo21#rules "GitHub - gbdev/gbcompo21: An OG gbdev game jam! Create original games, demos or homebrews for the original Game Boy (Color) and compete for glory (and a lot of prizes)!") places an emphasis that entries must be compliant to *known MBCs* and links to the [list of mappers](https://gbdev.io/pandocs/MBCs.html "MBCs - Pan Docs") in the *new* Pan Docs. It then goes on that MBC 5 and 3 are recommended, and that using "No MBC" is also allowed.
This leaves me with a lot of questions:

1. Does this pertain to how MBCs are implemented in emulators (and tagged in ROM headers of officially released cartridges) or how they are available in hardware? (both of those options would allow and disallow some)
2. Does this mean only those MBCs (or the "No MBC") as they are listed in that version of the Pan Docs are allowed?
3. Are really *all* of the MBCs that are listed in that version of the Pan docs allowed?
4. Do those MBCs need to be used to manage memory regions as specified or is repurposing of address lines, say, to remap ROM via RAM space, map RAM via ROM space, or both, permitted?
5. Is the "No MBC" variant with RAM ([example](https://shop.insidegadgets.com/product/gameboy-32kb-4kb-fram-flash-cart/ "[Discontinued] Gameboy 32KB ROM, 4KB FRAM Flash Cart – insideGadgets Shop")) permitted?
6. Can ROM space be made writable (["No MBC" example](https://shop.insidegadgets.com/product/gameboy-32kb-from-cart/ "Gameboy 32KB FROM Cart – insideGadgets Shop"))?
7. Is it permissible to require rumble (either via MBC5, or MBC3 with [non-standard extension](https://shop.insidegadgets.com/product/gameboy-4mb-32kb-fram-mbc3-with-rtc-flash-cart/ "Gameboy 4MB 32KB FRAM MBC3 with RTC Flash Cart (Works with Pokemon games/hacks like CC) – insideGadgets Shop")) for a game mechanic (e.g. Maniac/Simon with the rumble instead of tones/lights)?
8. Would a use of MBC7 (also referred to as MBC5+Tilt) and requiring the use of the accelerometer be permissible?
9. Extending on 8, is it permissible to attach RAM to an MBC7 (the only two released official gamepaks that used it, Kirby's Tilt'n'Tumble (US)/Kororo Kirby (JPN) and Command Master (JPN) had no RAM and only used a very small serial EEPROM for save data instead)?
10. Extending further on 8 and 9, and this may encroach on rule 12, would replacing the serial EEPROM with a different serial SPI device be permissible?
11. Though no known hardware implementation exists (as far as I know, wouldn't be a stretch to make one using FPGA/CPLD tho), and it doesn't appear to be listed in Pan Docs, can the [TPP1 mapper](https://github.com/TwitchPlaysPokemon/tpp1/blob/master/specification.md "tpp1/specification.md at master · TwitchPlaysPokemon/tpp1 · GitHub") be used? (BGB, which is emulation reference, supports it as of 1.5.9)
12. How far does rule 12 go, does it only apply to peripherals (GameLink, anything not in the cart) or everything non-standard about a cart? (PS: I totally did not intentionally make this question number 12 because of rule 12, fun coincidence)
13. Extending on 12, if only external hardware requirements are not allowed, would that include those that are commonplace, like say, Wi-Fi? (it's a bit of a technicality if a radio signal can be considered hardware, even if *some* hardware is required to provide it, if it is always there and you can do nothing about it but go inside a farraday cage, maybe)
14. If special cart configurations (numbers 4, 5, 6, 7, 9, 10, 13) are permitted, what would be required for an entry to be judged by running it on real hardware? Schematics, gerbers and BOM to build a cart or a finished and built cart? If the latter, where does one send one?

**Comment by ISSOtm** [comment]
Imo, your questions are covered by rule 2:

> The ROM file will be tested on real hardware (usually a DMG or a GBC) and on the BGB emulator.

The accepted configurations are those that will work on those. This implicitly excludes custom hardware and non-standard extensions. We might need to further restrict the MBC list to MBC1/3/5 to permit hardware testing on all our setups, though.

**Comment by dori4n** [comment]
> Imo, your questions are covered by rule 2

They aren't. I don't know what test equipment you have at your disposal. It is not described at all.

If only standard extensions are allowed, and MBC5 is included, do you have a rumble cart? (I just tried it, and BGB 1.5.9 does not support rumble with a capable gamepad like an Xbox controller, it seems)
As for MBC3, does that include MBC30 with the larger ROM and RAM space support (more specifically, do you have a 4MiB MBC30 flashcart with 64KiB of cart RAM)?
What hardware CPU revisions will you be using? (some of those have bugs to the point where features won't work, which affects, among others, sound output significantly)

Also, there was question number 14... 😗

**Comment by ISSOtm** [comment]
> They aren't. I don't know what test equipment you have at your disposal. It is not described at all.

Given that the intention for the compo is not only for the entries to run on the judges' setups, but on the larger public's as well, sticking to common configurations is the safe bet. Similarly, revision-specific behavior should be avoided.

The rule of thumb I would advise sticking to is that at least one judge will have any hardware configuration.

As for question 14, custom hardware is not allowed, as we want to keep this a software compo and not a hardware one. Official (= Nintendo-licensed), known configurations shall be used.

**Comment by dori4n** [comment]
> Similarly, revision-specific behavior should be avoided.

Okay, no volume sweep or abusing the NR43 registers it is, then... 😦

> at least one judge will have any hardware configuration

Does that mean any *and* all, or any *one of* all? 😉

> Official (= Nintendo-licensed), known configurations shall be used.

This again leaves open the opportunity for those that have never been used in a commercial game (there were some options available no developer decided to use), and then there's the Gameboy Camera... 😜

Lastly, since this is still unclear, do the judges have a rumble cart and/or a standard configuration MBC7/MBC5+Tilt cart and for the latter what's the size of the EEPROM (Korokoro Kirby used 512 byte and Command Master had 1KiB)?
Both of those would be easily made from a suitable OEM retail cart with an [adapter](https://github.com/JRodrigoTech/FLASH-ROM-Adapter-for-GameBoy "GitHub - JRodrigoTech/FLASH-ROM-Adapter-for-GameBoy: AM29F016 or AM29F032 flash memory adapter board to easily DIY a Game Boy flash cartridge"). For the former (MBC5 rumble cart), official developer cartridges from Nintendo were also available and listed in the programming manual.

**Comment by aaaaaa123456789** [comment]
Only some official MBC chips (MBC1, MBC2, MBC3 and MBC5, as well as no MBC at all) are allowed. The only exceptions are:
- While Nintendo only manufactured very specific MBC+ROM combinations, we will allow any power-of-two ROM size between 32 KiB and the maximum for the chosen chip. (This is simply a convenience feature, as any ROM image can be extended to fit a larger ROM chip by appending copies of itself.)
- The ROM+RAM combination (i.e., without an MBC, up to 32 KiB ROM and 8 KiB SRAM), with or without battery, will be accepted for compatibility, as many people have simple flash carts that do have SRAM but don't have an MBC. (This can be trivially emulated by any MBC1, MBC3 or MBC5 configuration.)
- The variants MBC30 and MBC1M are accepted, as they have been used in licensed games.
- Some official MBCs added extra components to the cart: MBC3/MBC30 carts could have an RTC, and MBC5 carts could have rumble. These combinations, and _only_ these combinations, will be accepted. In particular, this means it's impossible to have RTC and rumble in the same cart.

Anything not listed above will be rejected, as the goal of the competition is to make software, not hardware.

**Comment by dori4n** [comment]
^ This is a very good description. One more thing, no wait, actually two:
1. Are there restrictions to the cart RAM sizes, particularly for MBC30 and MBC5 with rumble? MBC30 can allow 64KiB of cart RAM, but a [common homebrew cart variant](https://github.com/HDR/MBC30-Flashcart "GitHub - HDR/MBC30-Flashcart: MBC30 Version of the MBC3 flashcart for 4MB roms") only has hardware for 32KiB. Also, MBC5 allows up to 128KiB of cart RAM, but no rumble cart ever used more than 32KiB.
2. Is prefilling cart RAM with specific content allowed (a save file would be supplied with the ROM file) the use of which is required to run the game (though, not necessarily modified by it)?

Oh no, @avivace you closed this too early... 😱

**Comment by aaaaaa123456789** [comment]
1. Since those combinations are coincidental and not really a restriction from the chip, it's okay to use the chips to their full capacity in those cases. Homebrew/flash cart limitations don't add restrictions to the rules, but it is always nice if you can fail gracefully if you detect one of those.
2. No. Much like manufactured carts were delivered with an unitialized RAM, you cannot assume anything about the initial RAM layout, except that it won't be intentionally filled in with malicious data (i.e., if you use some sort of initialization detection, the initial RAM won't be intentionally filled in with extremely unlikely data that will pass the detection but be invalid).

**Comment by dori4n** [comment]
> 2. No.

Aww... that's unfortunate.

> Much like manufactured carts were delivered with an unitialized RAM [...]

That's not true for all of them, some were intentionally initialized with zeroes, others with bonus content (one of them was Pokemon) if you got it at a special event. That was not required to run the game, of course.

**Comment by untoxa** [comment]
you are forgetting about one very tiny little thing: there should be an excellent original game with fine art and music designed around your key hardware quirk.

**Comment by dori4n** [comment]
> there should be an excellent original game with fine art and music designed around your key hardware quirk

I mean, that's the plan, sort of, still not sure if I can do it. I gotta find out about all the things I can't do first and then decide on which of my plethora of ideas to implement 😉
(Also, if you're curious, the pre-supplied save file was me trying to abuse RAM I don't need to be RAM as more ROM space to fit more of this "game with fine art and music" you were talking about...)

**Comment by untoxa** [comment]
rules clearly say: entry is a rom-file.
