### ISSUE TITLE
What exactly counts as NSFW?

### ISSUE THREAD

**Issue by eishiya** [gbdev/gbcompo21#9]
> 8. NSFW content is not allowed. Please keep it safe for work and avoid anything overly edgy or distasteful.

Rule 8 is pretty vague, as "NSFW" and "safe for work" can mean a whole lot of different things to different people. I realise it can't be made as clear as the more technical rules, but I some extra detail would be helpful.

The entry I'm working on has some mild swearing ("ass", "shit"), a couple of buttcracks, human and animal corpses, and exposed organs/bones (in glorious low definition). While I think they're all tasteful and don't feel unnecessary, I'd rather make changes than get disqualified because of this rule.

I ran some of our art by Proximity Sound a week or so ago and they said the gory stuff should be no problem, but recommended covering up the butts. They also wrote in reply to someone else on the GB Studio server that swearing should not be a problem and that the rule is intended to bar porn and the like. But that's not what the rule *says*, so some clarification would really help!

**Comment by bbbbbr** [comment]
If it meets ESRB-Teen then it should be fine.
https://en.wikipedia.org/wiki/Entertainment_Software_Rating_Board#Ratings

In general, if it's relatively tame and isn't trying to "push the boundary" it's probably ok. As the saying goes- it's hard to define it precisely (and we don't want to enumerate every single thing), but you likely know when it's getting iffy.
